### ISSUE TITLE
constant update nag

### ISSUE THREAD

**Issue by maclakey** [tmountjr/OctoPrint-Openmiko#1]
I found the OctoPrint-openmiko plugin recently and love it. Only problem is I keep getting notified of a 0.2.0 update, but it only installs the 0.1.0 version, even a clean install only does 0.1.0.

**Comment by worstimeline** [comment]
Same issue here. Uninstalling.

**Comment by tmountjr** [comment]
thanks for letting me know - this is my first plugin and offhand I'm not sure what might be causing this but I'll definitely take a look!

**Comment by tmountjr** [comment]
I've bumped up to v0.2.1 to address the issue (didn't increment the version number in code properly which I imagine meant that the code was updated to v0.2.0 but it still read as being v0.1.0.) This should allow v0.2.1 to install and then not keep nagging. I'll leave this open for a bit to make sure it's rolled out properly and is doing what it should be.

**Comment by tmountjr** [comment]
@suxmcgee @maclakey the new version is available via the software updater (just installed it on mine and it got the right one and didn't keep asking). Apologies for the delay but it should be good to go now. Can one or both of you confirm? I don't want to close it with just one verification.

**Comment by maclakey** [comment]
@tmountjr Thanks!  I'll try it now!  *update*  that fixed it!

**Comment by worstimeline** [comment]
> @suxmcgee @maclakey the new version is available via the software updater (just installed it on mine and it got the right one and didn't keep asking). Apologies for the delay but it should be good to go now. Can one or both of you confirm? I don't want to close it with just one verification.

I actually stopped using my wyzecam and just went back to a Logitech C922 until I can get the wyze-bridge docker install going. Sorry bud. Glad maclakey could confirm it fixed the update nag.
